language: node_js
node_js:
  - "lts/*"

install:
  - npm install
  - npm run build

script:
  - npm run test:coverage

after_success:
  - cat ./packages/*/js_coverage/lcov.info | coveralls
  - cat ./examples/*/js_coverage/lcov.info | coveralls
